{{ if .Values.systemDefaultValues.resourceSyncAgent.enabled}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: connectedclusters.arc.azure.com
  labels:
    azuresync: "true"
  annotations:
    resourceSync.arc.azure.com/ProviderNamespace: Microsoft.Kubernetes
    resourceSync.arc.azure.com/ResourceType: connectedCluster
  creationTimestamp: null
spec:
  group: arc.azure.com
  version: v1beta1
  names:
    kind: ConnectedCluster
    plural: connectedclusters
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ConnectedCluster is the object for the ConnectedClusters
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ConnectedClusterSpec defines the desired state of
            ConnectedCluster
          properties:
            azureResourceId:
              description: AzureResourceId is the armId of the cluster
              type: string
          type: object
        status:
          description: ConnectedClusterStatus defines the observed state
            of ConnectedCluster
          properties:
            nodeCount:
              description: NodeCount is the no of the nodes present in the cluster 
              type: integer
            kubernetesAPIServerVersion:
              description: KubernetesAPIServerVersion is the kubernetes version the cluster is running on
              type: string
            arcAgentVersion:
              description: ArcAgentVersion is the version of the arc agents in the cluster
              type: string
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
{{end}}