{{- if .Values.systemDefaultValues.spnOnboarding }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-agent
  namespace: azure-arc
  labels:
    app.kubernetes.io/name:  azure-arc-k8s
    app.kubernetes.io/component: connect-agent
  annotations:
    description: {{ .Chart.Description }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azure-arc-k8s
      app.kubernetes.io/component: connect-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azure-arc-k8s
        app.kubernetes.io/component: connect-agent
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/azure-proxy-config.yaml") . | sha256sum }}
    spec:
      serviceAccountName: azure-arc-operatorsa
{{- if .Values.systemDefaultValues.azureArcAgents.affinity }}
      affinity:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.affinity | indent 8 }}
{{- end }}
{{- if .Values.systemDefaultValues.azureArcAgents.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.nodeSelector | indent 8 }}
{{- end }}
      containers:      
        - name: connect-agent
          image: "{{ .Values.systemDefaultValues.image.repository }}/{{ .Values.systemDefaultValues.image.releaseName }}/{{ index .Values.systemDefaultValues "connect-agent" "image" }}:{{ index .Values.systemDefaultValues "connect-agent" "tag" }}"
          imagePullPolicy: {{ .Values.systemDefaultValues.image.imagePullPolicy }}
{{- if .Values.systemDefaultValues.azureArcAgents.resources  }}
          resources:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.resources | indent 12 }}
{{- end }}
          envFrom:
          - configMapRef:
              name: azure-clusterconfig
          - configMapRef:
              name: azure-proxy-config
          env:
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: azure-arc-onboarding
                key: value
          {{ if .Values.systemDefaultValues.IsDebug}}
          ports:
            - containerPort: 40000
              name: debug
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          {{end}}
{{- end }}