{{- if index .Values.systemDefaultValues "connectproxy-agent"  "enabled" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectproxy-agent
  namespace: azure-arc
  labels:
    app.kubernetes.io/name:  azure-arc-k8s
    app.kubernetes.io/component: connectproxy-agent
  annotations:
    description: {{ .Chart.Description }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azure-arc-k8s
      app.kubernetes.io/component: connectproxy-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azure-arc-k8s
        app.kubernetes.io/component: connectproxy-agent
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/azure-proxy-config.yaml") . | sha256sum }}
    spec:
      serviceAccountName: azure-arc-operatorsa
{{- if .Values.systemDefaultValues.azureArcAgents.affinity }}
      affinity:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.affinity | indent 8 }}
{{- end }}
{{- if .Values.systemDefaultValues.azureArcAgents.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--logtostderr=true"
            - "--v=2"
          ports:
            - containerPort: 8443
              name: https
{{- if .Values.systemDefaultValues.kubeRbacProxy.resources }}
          resources:
{{ toYaml .Values.systemDefaultValues.kubeRbacProxy.resources | indent 12 }}
{{- end }}
          envFrom:
            - configMapRef:
                name: azure-proxy-config
        - name: connectproxy-agent
          image: "{{ .Values.systemDefaultValues.image.repository }}/{{ .Values.systemDefaultValues.image.releaseName }}/{{ index .Values.systemDefaultValues "connectproxy-agent" "image" }}:{{ index .Values.systemDefaultValues "connectproxy-agent" "tag" }}"
          imagePullPolicy: {{ .Values.systemDefaultValues.image.imagePullPolicy }}
{{- if .Values.systemDefaultValues.azureArcAgents.resources  }}
          resources:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.resources | indent 12 }}
{{- end }}
          envFrom:
            - configMapRef:
                name: azure-clusterconfig
            - configMapRef:
                name: azure-proxy-config
          env:
            - name: CONNECT_DP_ENDPOINT_OVERRIDE
              value: {{ index .Values.systemDefaultValues "connectproxy-agent" "connect_dp_endpoint_override" }}
            - name: PROXY_VERSION
              value: {{ index .Values.systemDefaultValues "connectproxy-agent" "version" }}
            - name: NOTIFICATION_DP_ENDPOINT_OVERRIDE
              value: {{ index .Values.systemDefaultValues "connectproxy-agent" "notification_dp_endpoint_override" }}
        - name: fluent-bit
          image: "{{ .Values.systemDefaultValues.image.repository }}/{{ .Values.systemDefaultValues.image.releaseName }}/{{ index .Values.systemDefaultValues "fluent-bit" "image" }}:{{ index .Values.systemDefaultValues "fluent-bit" "tag" }}"
          imagePullPolicy: {{ .Values.systemDefaultValues.image.imagePullPolicy }}
          {{ if eq .Values.global.kubernetesDistro "openshift"}}
          securityContext:
            privileged: true
          {{end}}
{{ $fluentBit := index .Values.systemDefaultValues "fluent-bit" "resources" }}
{{- if  $fluentBit  }}
          resources:
{{ $fluentBit | toYaml | indent 12 }}
{{- end }}
          envFrom:
            - configMapRef:
                name: azure-clusterconfig
            - configMapRef:
                name: azure-proxy-config
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_TYPE
              value: "ConnectAgent"
            - name: AGENT_NAME
              value: "ConnectProxyAgent"
          ports:
          - containerPort: 2020    
          volumeMounts:
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: fluentbit-clusterconfig
            mountPath: /fluent-bit/etc/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log  
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluentbit-clusterconfig
          configMap:
            name: azure-fluentbit-config  
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: azure-arc-k8s
    app.kubernetes.io/component: connectproxy-agent
  name: connectproxy-agent-metrics-service
  namespace: azure-arc
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    app.kubernetes.io/name: azure-arc-k8s
    app.kubernetes.io/component: connectproxy-agent
{{- end }}