apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  namespace: azure-arc
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      namespace: azure-arc
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: azure-arc-operatorsa
      restartPolicy: Never
{{- if .Values.systemDefaultValues.azureArcAgents.affinity }}
      affinity:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.affinity | indent 8 }}
{{- end }}
{{- if .Values.systemDefaultValues.azureArcAgents.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: post-install-job
          image: "bitnami/kubectl:latest"
{{- if and .Values.systemDefaultValues.resourceSyncAgent.enabled .Values.systemDefaultValues.extensionoperator.enabled }}
          command: ["kubectl", "delete", "crd", "gitconfigs.clusterconfig.azure.com","azureclusteridentityrequests.clusterconfig.azure.com", "connectedclusters.arc.azure.com", "extensionconfigs.clusterconfig.azure.com"]
{{- else if .Values.systemDefaultValues.resourceSyncAgent.enabled}}
          command: ["kubectl", "delete", "crd", "gitconfigs.clusterconfig.azure.com","azureclusteridentityrequests.clusterconfig.azure.com", "connectedclusters.arc.azure.com"]
{{- else }}
          command: ["kubectl", "delete", "crd", "gitconfigs.clusterconfig.azure.com","azureclusteridentityrequests.clusterconfig.azure.com"]
{{- end }}
