trigger:
  branches:
    include:
    - main
    - release-v*
  paths:
    include:
      - charts/osm-arc/Chart.yaml
      - scripts/add-extension.sh
      - scripts/update-extension.sh

pr:
  branches:
    include:
    - main
    - release-v*
  paths:
    include:
      - charts/osm-arc/Chart.yaml
      - scripts/add-extension.sh
      - scripts/update-extension.sh

variables:
  chart.name: osm-arc
  chart.path: $(System.DefaultWorkingDirectory)/charts/$(chart.name)
  image.dir: $(Build.ArtifactStagingDirectory)
  image.artifact.name: drop
  KUBECONFIG: $(System.DefaultWorkingDirectory)/kubeconfig.json
  upstream.repo: https://github.com/openservicemesh/osm

stages: 
- stage: run_e2e
  jobs:
    - template: ../pr-job/e2e-aks-arc.yaml
      parameters:
        releaseE2E: true
