trigger:
  branches:
    include:
    - main
    - release-v*
  paths:
    exclude:
      - docs/*
      - conformance/*
      - tools/*
      - .github/*
      - scripts/register-extension-prod.sh

pr:
  branches:
    include:
    - main
    - release-v*
  paths:
    exclude:
      - docs/*
      - conformance/*
      - tools/*
      - .github/*
      - scripts/register-extension-prod.sh

variables:
  chart.name: osm-arc
  chart.path: $(System.DefaultWorkingDirectory)/charts/$(chart.name)
  image.dir: $(Build.ArtifactStagingDirectory)
  image.artifact.name: drop
  KUBECONFIG: $(System.DefaultWorkingDirectory)/kubeconfig.json
  upstream.repo: https://github.com/Azure/osm

stages: 
- stage: run_e2e
  jobs:
    - template: e2e-aks-arc.yaml
