{{ if .Values.systemDefaultValues.fluxlogsagent.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-logs-agent
  namespace: azure-arc
  labels:
    app.kubernetes.io/name: azure-arc-k8s
    app.kubernetes.io/component: flux-logs-agent
  annotations:
    description: {{ .Chart.Description }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azure-arc-k8s
      app.kubernetes.io/component: flux-logs-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azure-arc-k8s
        app.kubernetes.io/component: flux-logs-agent
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/azure-proxy-config.yaml") . | sha256sum }}
    spec:
      serviceAccountName: azure-arc-operatorsa
{{- if .Values.systemDefaultValues.azureArcAgents.affinity }}
      affinity:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.affinity | indent 8 }}
{{- end }}
{{- if .Values.systemDefaultValues.azureArcAgents.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8081/"
            - "--logtostderr=true"
            - "--v=2"
          ports:
            - containerPort: 8443
              name: https
{{- if .Values.systemDefaultValues.kubeRbacProxy.resources }}
          resources:
{{ toYaml .Values.systemDefaultValues.kubeRbacProxy.resources | indent 12 }}
{{- end }}
          envFrom:
            - configMapRef:
                name: azure-proxy-config
        - name: flux-logs-agent
          image: "{{ .Values.systemDefaultValues.image.repository }}/{{ .Values.systemDefaultValues.image.releaseName }}/{{ .Values.systemDefaultValues.fluxlogsagent.image }}:{{ .Values.systemDefaultValues.fluxlogsagent.tag }}"
          imagePullPolicy: {{ .Values.systemDefaultValues.image.imagePullPolicy }}
{{- if .Values.systemDefaultValues.azureArcAgents.resources  }}
          resources:
{{ toYaml .Values.systemDefaultValues.azureArcAgents.resources | indent 12 }}
{{- end }}
          envFrom:
            - configMapRef:
                name: azure-clusterconfig
            - configMapRef:
                name: azure-proxy-config
          ports:
          - containerPort: 8080
          {{ if .Values.systemDefaultValues.IsDebug}}
          - containerPort: 40000
            name: debug
            protocol: TCP
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
          {{end}}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: azure-arc-k8s
    app.kubernetes.io/component: flux-logs-agent
  name: flux-logs-agent-metrics-service
  namespace: azure-arc
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    app.kubernetes.io/name: azure-arc-k8s
    app.kubernetes.io/component: flux-logs-agent
---
kind: Service
apiVersion: v1
metadata:
  name: flux-logs-agent
  namespace: azure-arc
spec:
  selector:
    app.kubernetes.io/name: azure-arc-k8s
    app.kubernetes.io/component: flux-logs-agent
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
{{end}}
