apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-clusterconfig
  namespace: azure-arc
data:
  AZURE_RESOURCE_NAME: {{ .Values.global.resourceName }}
  AZURE_SUBSCRIPTION_ID: {{ .Values.global.subscriptionId }}
  AZURE_TENANT_ID: {{ .Values.global.tenantId }}
  {{- if .Values.systemDefaultValues.spnOnboarding }}
  {{- if eq .Values.systemDefaultValues.isClientSecretAToken false }}
  AZURE_CLIENT_ID: {{ .Values.global.clientId }}
  {{- end }}
  {{- end }}
  IS_CLIENT_SECRET_A_TOKEN: "{{ .Values.systemDefaultValues.isClientSecretAToken }}"
  AZURE_RESOURCE_GROUP: {{ .Values.global.resourceGroupName }}
  AZURE_REGION: {{ .Values.global.location }}
  ONBOARDING_SECRET_NAME: "azure-arc-connect-privatekey"
  ONBOARDING_SECRET_NAMESPACE: "azure-arc"
  TAGS: {{ .Values.global.tags }}
  MANAGED_IDENTITY_AUTH: "{{ .Values.systemDefaultValues.optIn.ManagedIdentityAuth }}"
  CLUSTER_TYPE: {{ index .Values.systemDefaultValues "config-agent" "cluster_type" }}{{ if index .Values.systemDefaultValues "azureArcAgents" "config_dp_endpoint_override" }}
  DP_ENDPOINT_OVERRIDE: {{ index .Values.systemDefaultValues "azureArcAgents" "config_dp_endpoint_override" }}{{ end }}
  FLUX_CLIENT_DEFAULT_LOCATION: {{ index .Values.systemDefaultValues "config-agent" "flux_client_default_location" }}
  AZURE_ARC_AGENT_VERSION: {{ .Values.systemDefaultValues.azureArcAgents.version }}
  HELM_AUTO_UPDATE_CHECK_FREQUENCY_IN_MINUTES: "{{ .Values.systemDefaultValues.azureArcAgents.updateCheckFrequencyInMinutes }}"
  AZURE_ARC_AUTOUPDATE: "{{ .Values.systemDefaultValues.azureArcAgents.autoUpdate }}"
  ARC_AGENT_RELEASE_TRAIN: {{.Values.systemDefaultValues.azureArcAgents.releaseTrain}}
  ARC_AGENT_HELM_CHART_NAME: "{{ .Chart.Name }}"
  AZURE_ARC_RELEASE_NAME: "{{ .Release.Name }}"
  AZURE_ARC_HELM_NAMESPACE: "{{ .Release.Namespace }}"
  DEBUG_LOGGING: "{{ .Values.systemDefaultValues.debugLogging }}"
  NO_AUTH_HEADER_DATA_PLANE: "{{ .Values.systemDefaultValues.noAuthHeaderDataPlane }}"
  EXTENSION_OPERATOR_ENABLED: "{{ .Values.systemDefaultValues.extensionoperator.enabled }}"
  GITOPS_ENABLED: "{{ .Values.systemDefaultValues.gitops.enabled }}"
  FLUX_UPSTREAM_SERVICE_ENABLED: "{{ .Values.systemDefaultValues.fluxlogsagent.enabled}}"
  KUBERNETES_TENANTID: "{{ .Values.global.kubernetesTenantId }}"
  KUBERNETES_SERVER_APPID: "{{ .Values.global.kubernetesServerId }}"
  KUBERNETES_CLIENT_APPID: "{{ .Values.global.kubernetesClientId }}"
  AZURE_ENVIRONMENT: "{{ .Values.global.azureEnvironment }}"
