{{- if eq .Values.systemDefaultValues.noAuthHeaderDataPlane false}}
{{- if eq .Values.systemDefaultValues.spnOnboarding true}}
apiVersion: v1
kind: Secret
metadata:
  name: azure-arc-onboarding
  namespace: azure-arc
type: Opaque
data:
  value: {{ .Values.global.clientSecret | b64enc }}
{{- end }}
---
{{- if eq .Values.systemDefaultValues.spnOnboarding false }}
apiVersion: v1
kind: Secret
metadata:
  name: azure-arc-connect-privatekey
  namespace: azure-arc
type: Opaque
stringData: 
   privateKey: {{ .Values.global.onboardingPrivateKey | quote }}
{{- end }}
{{- end }}
