apiVersion: apps/v1
kind: Deployment
metadata:
  name: osm-controller
  labels:
    app: osm-controller
    meshName: {{ .Values.OpenServiceMesh.meshName }}
    {{ if .Values.OpenServiceMesh.enforceSingleMesh }}enforceSingleMesh: "true"{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osm-controller
  template:
    metadata:
      labels:
        app: osm-controller
      annotations:
          checksum/config: {{ print .Values.openServiceMesh | sha256sum }}
    spec:
      serviceAccountName: arc-osm-service-account
      containers:
        - name: osm-controller
          image: "mcr.microsoft.com/oss/openservicemesh/osm-controller:{{ .Values.OpenServiceMesh.osmImageTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: "admin-port"
              containerPort: 15000
            - name: "osm-port"
              containerPort: 15128
          command: ['/osm-controller']
          args: [
            "--verbosity", "trace",
            "--osm-namespace", "{{.Values.OpenServiceMesh.namespace}}",
            "--mesh-name", "{{.Values.OpenServiceMesh.meshName}}",
            "--init-container-image", "mcr.microsoft.com/oss/openservicemesh/init:{{ .Values.OpenServiceMesh.osmImageTag }}",
            "--sidecar-image", "mcr.microsoft.com/oss/envoyproxy/envoy:{{.Values.OpenServiceMesh.sidecarImageTag}}",
            "--webhook-config-name", "arc-osm-webhook-{{.Values.OpenServiceMesh.meshName}}",
            "--ca-bundle-secret-name", "{{.Values.OpenServiceMesh.caBundleSecretName}}",
            "--certificate-manager", "{{.Values.OpenServiceMesh.certificateManager}}",
            "--cert-manager-issuer-name", "{{.Values.OpenServiceMesh.certmanager.issuerName}}",
            "--cert-manager-issuer-kind", "{{.Values.OpenServiceMesh.certmanager.issuerKind}}",
            "--cert-manager-issuer-group", "{{.Values.OpenServiceMesh.certmanager.issuerGroup}}",
          ]
          resources:
            limits:
              cpu: 1.5
              memory: 256M
            requests:
              cpu: 0.5
              memory: 32M
          readinessProbe:
            initialDelaySeconds: 1
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              path: /health/ready
              port: 9091
          livenessProbe:
            initialDelaySeconds: 1
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              path: /health/alive
              port: 9091
          env:
            # The CONTROLLER_POD_NAME env variable sets pod name dynamically, used by osm-controller to register events
            - name: CONTROLLER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      {{- if .Values.OpenServiceMesh.enableFluentbit }}
        - name: {{ .Values.OpenServiceMesh.fluentBitImage.name }}
          image: {{ .Values.OpenServiceMesh.fluentBitImage.registry }}/fluent-bit:{{ .Values.OpenServiceMesh.fluentBitImage.tag }}
          imagePullPolicy: {{ .Values.OpenServiceMesh.fluentBitImage.pullPolicy }}
          volumeMounts:
          - name: config
            mountPath: /fluent-bit/etc
            readOnly: true 
          - name: var-log-containers
            mountPath: /var/log/containers
            readOnly: true
          - name: var-log-pods
            mountPath: /var/log/pods
            readOnly: true
          - name: var-lib-containers
            mountPath: /var/lib/docker/containers
            readOnly: true
        {{- end }}
    {{- if .Values.OpenServiceMesh.enableFluentbit }}
      volumes:
      - name: config
        configMap:
          name: fluentbit-configmap
      - name: var-log-containers
        hostPath:
          path: /var/log/containers
      - name: var-log-pods
        hostPath:
          path: /var/log/pods
      - name: var-lib-containers
        hostPath:
          path: /var/lib/docker/containers
     {{- end }}
     