jobs:
  - job: test_osm_aks_addon
    pool: staging-pool
    workspace:
      clean: all
    steps:
    - template: ../templates/install-helm3.yaml
    - template: ../templates/checkout-upstream-repo.yaml
    - template: ../templates/aks-setup.yaml
    - template: ../templates/aks-addon-templates/enable-osm-aks-addon.yaml
    - template: ../templates/run-upstream-e2e.yaml
      parameters:
        aksAddonRun: true
    - template: ../templates/debug-resources.yaml
    - template: ../templates/aks-cleanup.yaml
