apiVersion: clusterconfig.azure.com/v1beta1
kind: AzureExtensionIdentity
metadata:
  name: osm
  namespace: azure-arc
spec:
  serviceAccounts:
    - name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
  tokenNamespace: {{ .Release.Namespace }}
