apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osm-identity-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openservicemesh.io
    app.kubernetes.io/instance: {{ .Values.osm.osm.meshName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
rules:
  - apiGroups: [ 'clusterconfig.azure.com' ]
    resources: [ 'azureclusteridentityrequests' ]
    verbs: [ 'get', 'create' ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: osm-identity-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openservicemesh.io
    app.kubernetes.io/instance: {{ .Values.osm.osm.meshName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osm-identity-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
