apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osm-identity-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osm.arcLabels" . | nindent 4 }}
rules:
  - apiGroups: [ 'clusterconfig.azure.com' ]
    resources: [ 'azureclusteridentityrequests' ]
    verbs: [ 'get', 'create' ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: osm-identity-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osm.arcLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osm-identity-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
