apiVersion: apps/v1
kind: Deployment
metadata:
  name: osm-metrics-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: osm-metrics-agent
    {{- include "osm.arcLabels" . | nindent 4 }}
  {{- if (ne .Values.Azure.Cluster.Distribution "openshift") }}
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osm-metrics-agent
  template:
    metadata:
      labels:
        app: osm-metrics-agent
        {{- include "osm.arcLabels" . | nindent 8 }}
      {{- if (ne .Values.Azure.Cluster.Distribution "openshift") }}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      {{- end }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      serviceAccount: {{ .Release.Name }}
      containers:
        - name: mdm
          image: linuxgeneva-microsoft.azurecr.io/genevamdm:master_20220401.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          env:
            - name: ROLEINSTANCE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CONFIG_OVERRIDES_FILE
              value: /tmp/geneva_mdm/mdmconfig.json
            - name: MDM_INPUT
              value: statsd_udp,statsd_tcp
            - name: MDM_LOG_LEVEL
              value: "Info"
          volumeMounts:
            - name: mdm-config
              mountPath: /tmp/geneva_mdm
        - name: msi-adapter
          image: mcr.microsoft.com/azurearck8s/msi-adapter:1.0.6
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          env:
            - name: TOKEN_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: EXTENSION_ARMID
              value: {{ .Values.Azure.Extension.ResourceId }}
            - name: EXTENSION_NAME
              value: {{ .Values.Azure.Extension.Name }}
            - name: CLUSTER_TYPE
              value: ConnectedClusters
            - name: CLUSTER_IDENTITY
              value: "false"
            - name: MANAGED_IDENTITY_AUTH
              value: "true"
            - name: TEST_MODE
              value: "false"
          securityContext:
            runAsUser: 0
            capabilities:
              add:
                - NET_ADMIN
            {{- if eq .Values.Azure.Cluster.Distribution "openshift" }}
            privileged: true
            {{- end }}
        - name: prom-mdm-converter
          image: upstreamarc.azurecr.io/prom-mdm-converter:v1.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          env:
            - name: SERVER_PORT
              value: "8090"
            - name: GENEVA_DEFAULT_MDM_NAMESPACE
              value: {{ .Values.Azure.Cluster.Region }}
            - name: GENEVA_ACCOUNT_NAME
              value: AzureServiceMesh
            - name: EXTENSION_RESOURCE_ID
              value: {{ .Values.Azure.Extension.ResourceId }}
        - name: telegraf
          image: mcr.microsoft.com/oss/mirror/docker.io/library/telegraf:1.21
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - name: telegraf-conf
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
      volumes:
        - name: mdm-config
          configMap:
            name: osm-mdm-config
        - name: telegraf-conf
          configMap:
            name: osm-telegraf-config
