apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-mdm-config
  namespace: {{ .Release.Namespace }}
data:
  mdmconfig.json: "{\"imdsInfo\":[{ \"account\": \"{{ .Values.metrics.mdm.accountName }}\" }]}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-telegraf-config
  namespace: {{ .Release.Namespace }}
data:
  telegraf.conf: |-
    [agent]
      interval = "60s"
      flush_interval = "10s"
      metric_batch_size = 250
      metric_buffer_limit = 1000

    [[inputs.prometheus]]
      monitor_kubernetes_pods = true
      kubernetes_label_selector = "app.kubernetes.io/component=osm-controller"
      monitor_kubernetes_pods_namespace = "arc-osm-system"
      bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
      tls_ca = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      insecure_skip_verify = true
      namedrop = ["rest_client_requests_*", "rest_client_request_*", "go_memstats_gc_*", "go_memstats_stack_*", "go_threads*", "go_memstats_mcache_*_bytes", "go_memstats_mspan_*_bytes", "go_memstats_last*", "go_memstats_next*", "go_memstats_other*", "go_memstats_sys*", "go_memstats_heap_idle_bytes", "go_memstats_heap_inuse_bytes", "go_memstats_heap_objects", "go_memstats_heap_released_bytes", "go_memstats_heap_sys_bytes", "process_*_fds", "process_threads_*", "process_*_pagefault_*", "process_disk_*", "process_*_context_switches_*", "process_num*", "process_open*", "process_resident*", "process_working*", "dotnet_collection_count_total*", "dotnet_total_memory_bytes", "go_gc_duration_seconds", "go_goroutines", "go_info", "internal_*", "workqueue_*", "kubernetes_node", "version_*"]

    [[outputs.http]]
      ## URL is the address to send metrics to
      url = "http://{{ .Values.metrics.telegraf.prometheusRemoteWriteUrl }}:{{ .Values.metrics.telegraf.prometheusRemoteWritePort }}/push"

      ## Data format to output.
      data_format = "prometheusremotewrite"

      [outputs.http.headers]
        Content-Type = "application/x-protobuf"
        Content-Encoding = "snappy"
        X-Prometheus-Remote-Write-Version = "0.1.0"

    {{ if .Values.metrics.telegraf.debugLogging }}
    [[outputs.file]]
      files = ["stdout"]
    {{ end }}
