apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-telegraf-config
  namespace: {{ .Release.Namespace }}
data:
  telegraf.conf: |-
    [agent]
      interval = "60s"
      flush_interval = "10s"
      metric_batch_size = 250
      metric_buffer_limit = 1000

    [[inputs.prometheus]]
      metric_version = 2

      monitor_kubernetes_pods = true
      kubernetes_label_selector = "app=osm-controller"
      monitor_kubernetes_pods_namespace = "arc-osm-system"
      bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
      tls_ca = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      insecure_skip_verify = true
      response_timeout = "15s"

    [[outputs.http]]
      ## URL is the address to send metrics to
      url = "http://localhost:8090/push"

      ## Data format to output.
      data_format = "prometheusremotewrite"

      [outputs.http.headers]
        Content-Type = "application/x-protobuf"
        Content-Encoding = "snappy"
        X-Prometheus-Remote-Write-Version = "0.1.0"

    [[outputs.file]]
      files = ["stdout"]
