jobs: 
  - job: push_osm_arc_plugin
    pool: staging-pool
    workspace: 
      clean: all
    steps:
    - template: ../templates/install-oras.yaml
    - template: ../templates/build-conf-test-image.yaml
    - template: ../templates/push-conf-image-acr.yaml
