jobs: 
  - job: nightly_image_scan
    pool: staging-pool-amd64-mariner-2
    workspace: 
      clean: all
    steps:
    - template: ../templates/build-conf-test-image.yaml
      parameters:
        imageScan: true
    - template: ../templates/install-trivy.yaml
    - template: ../templates/trivy-scan-image.yaml
      parameters:
        imageName: osm-arc-conformance
        imageTag: test
