# Default values for osm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
OpenServiceMesh:
  osmImageTag: v0.4.1
  sidecarImageTag: v1.15.0 
  certificateManager: tresor
  certmanager:
    issuerName: osm-ca
    issuerKind: Issuer
    issuerGroup: cert-manager
  serviceCertValidityMinutes: 1440
  caBundleSecretName: osm-ca-bundle
  enableDebugServer: true
  enablePermissiveTrafficPolicy: true
  enableEgress: false
  meshName: osm
  useHTTPSIngress: false
  envoyLogLevel: error
  namespace: arc-osm-system

  # The following section configures a destination where to send
  # tracing data. Current implementation supports only Zipkin format
  # backends (https://github.com/openservicemesh/osm/issues/1596)
  tracing:

    ## Toggles Envoy's tracing functionality on/off
    ## for all proxies in the mesh.
    enable: true

    # Tracing destination cluster
    address: "jaeger.osm-system.svc.cluster.local"

    # Destination port for the listener
    port: 9411

    # Destination's API or collector endpoint where the spans will
    # be sent to
    endpoint: "/api/v2/spans"
