parameters: 
  - name: releaseE2E #runs update tests specific to cutting new releases
    type: boolean
    default: false

jobs: 
  - job: test_osm_chart_arc_cluster
    pool: Upstream Pool
    workspace: 
      clean: all
    steps: 
    - template: templates/install-helm3.yaml
    - template: templates/install-oras.yaml
    - template: templates/install-bats.yaml
    - template: templates/package-helm-chart.yaml
    - ${{ if eq(parameters.releaseE2E, true) }}:
      - template: templates/publish-helm-chart.yaml
        parameters:
          releaseTag: true
    - ${{ if eq(parameters.releaseE2E, false) }}:
      - template: templates/publish-helm-chart.yaml
    - template: templates/aks-setup.yaml
    - template: templates/enable-arc.yaml
    - ${{ if eq(parameters.releaseE2E, true) }}:
      - template: templates/get-latest-tag.yaml
      - template: templates/add-arc-extension.yaml
        parameters: 
          imageTag: $(LATEST_TAG)
      - script: |
          make test-e2e
        displayName: "Run osm-azure e2e tests on latest release chart"
        env: 
          EXTENSION_TAG: $(LATEST_TAG)
          KUBECONFIG: $(System.DefaultWorkingDirectory)/kubeconfig.json
      - template: templates/update-arc-addon.yaml
    - ${{ if eq(parameters.releaseE2E, false) }}:
      - template: templates/add-arc-extension.yaml
    - script: |
        make test-e2e
      displayName: "Run osm-azure e2e tests"
      env: 
        EXTENSION_TAG: $(CHART_TAG)
        KUBECONFIG: $(System.DefaultWorkingDirectory)/kubeconfig.json
    - template: templates/run-upstream-e2e.yaml
    - template: templates/debug-resources.yaml
    - template: templates/acr-cleanup.yaml
    - template: templates/aks-cleanup.yaml
