# Default values for osm-arc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Values populated by Azure Arc K8s RP during the installation of the extension
Azure:
  Cluster:
    # This variable is populated by the Azure Arc RP
    # Expected values: https://github.com/Azure/azure-cli-extensions/blob/0bf8ef35e22d520708dc3fc99179f3f2e1a87332/src/connectedk8s/azext_connectedk8s/custom.py#L436
    Distribution: <cluster_distribution>

OpenServiceMesh:
    ignoreNamespaces: "kube-system azure-arc arc-osm-system"

osm:
  OpenServiceMesh:
    enableDebugServer: false
    enablePermissiveTrafficPolicy: true
    image:
      registry: mcr.microsoft.com/oss/openservicemesh
    enforceSingleMesh: true
    enablePrometheus: false
    deployJaeger: false
    webhookConfigNamePrefix: arc-osm-webhook
    sidecarImage: mcr.microsoft.com/oss/envoyproxy/envoy:v1.17.2
    osmcontroller:
      podLabels: {
        app.kubernetes.io/component: osm-controller
      }
    injector:
      podLabels: {
        app.kubernetes.io/component: osm-controller
      }

alpine:
  image:
    name: "mcr.microsoft.com/azure-policy/alpine"
    tag: "prod_20200505.1"
