# Default values for osm-arc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Values populated by Azure Arc K8s RP during the installation of the extension
Azure:
  Cluster:
    Distribution: <cluster_distribution>
  Extension:
    Name: ""
    ResourceId: ""

OpenServiceMesh:
  ignoreNamespaces: "kube-system azure-arc arc-osm-system"
  testedDistros: "aks gke eks openshift rancher_rke"

osm:
  osm:
    enableDebugServer: false
    enablePermissiveTrafficPolicy: true
    image:
      registry: mcr.microsoft.com/oss/openservicemesh
      tag: v1.0.0
    enforceSingleMesh: true
    enableReconciler: true
    deployPrometheus: false
    deployJaeger: false
    webhookConfigNamePrefix: arc-osm-webhook
    sidecarImage: mcr.microsoft.com/oss/envoyproxy/envoy:v1.19.1
    osmController:
      podLabels: {
        app.kubernetes.io/component: osm-controller
      }
    injector:
      podLabels: {
        app.kubernetes.io/component: osm-controller
      }
    prometheus:
      image: mcr.microsoft.com/oss/prometheus/prometheus:v2.18.1
    curlImage: mcr.microsoft.com/oss/tutum/curl
    tracing:
      image: mcr.microsoft.com/oss/jaegertracing/all-in-one
    grafana:
      image: mcr.microsoft.com/oss/grafana/grafana:v8.2.2
      rendererImage: mcr.microsoft.com/oss/grafana/grafana-image-renderer:v3.2.1

metrics:
  mdm:
    image:
      repository: linuxgeneva-microsoft.azurecr.io/genevamdm
      tag: master_20220216.1
      pullPolicy: IfNotPresent
    metricEndpoint: https://az-int.int.microsoftmetrics.com/
    accountName: OsmGenevaTesting
    environment: test # test | prod TODO

  msiAdapter:
    image:
      repository: azurearcfork8sdev.azurecr.io/arc-preview/msi-adapter
      tag: 0.0.10
      pullPolicy: IfNotPresent

  telegraf:
    image:
      repository: mcr.microsoft.com/oss/mirror/docker.io/library/telegraf
      tag: 1.21
      pullPolicy: IfNotPresent
    debugLogging: true
    prometheusRemoteWritePort: 8090
    prometheusRemoteWriteUrl: 127.0.0.1

  promMdmConverter:
    image:
      repository: stardotstar/provider-azure-arc-metrics-agent # TODO: update
      tag: v1.1.0-rc.0-linux-amd64
      pullPolicy: IfNotPresent

alpine:
  image:
    name: "mcr.microsoft.com/azure-policy/alpine"
    tag: "prod_20200505.1"

kubectl:
  image:
    name: "mcr.microsoft.com/oss/kubernetes/kubectl"
    tag: "v1.22.3"

helm:
  image:
    name: "mcr.microsoft.com/oss/openservicemesh/osm-arc/tools/osm-helm-cli"
    tag: "3.7.1"
