# Default values for osm-arc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Values populated by Azure Arc K8s RP during the installation of the extension
Azure:
  Cluster:
    Distribution: <cluster_distribution>

OpenServiceMesh:
  ignoreNamespaces: "kube-system azure-arc arc-osm-system"
  testedDistros: "aks gke eks openshift rancher_rke"

osm:
  OpenServiceMesh:
    enableDebugServer: false
    enablePermissiveTrafficPolicy: true
    image:
      registry: mcr.microsoft.com/oss/openservicemesh
    enforceSingleMesh: true
    deployPrometheus: false
    deployJaeger: false
    webhookConfigNamePrefix: arc-osm-webhook
    sidecarImage: mcr.microsoft.com/oss/envoyproxy/envoy:v1.18.3
    osmController:
      podLabels: {
        app.kubernetes.io/component: osm-controller
      }
    injector:
      podLabels: {
        app.kubernetes.io/component: osm-controller
      }

alpine:
  image:
    name: "mcr.microsoft.com/azure-policy/alpine"
    tag: "prod_20200505.1"

kubectl:
  image:
    name: "bitnami/kubectl"
    tag: "latest"

helm:
  image:
    name: "alpine/helm"
    tag: "latest"