# Default values for osm-arc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Values populated by Azure Arc K8s RP during the installation of the extension
Azure:
  Cluster:
    # This variable is populated by the Azure Arc RP
    # Expected values: https://github.com/Azure/azure-cli-extensions/blob/0bf8ef35e22d520708dc3fc99179f3f2e1a87332/src/connectedk8s/azext_connectedk8s/custom.py#L436
    Distribution: <cluster_distribution>
    Region: ""
  Extension:
    Name: ""
    ResourceId: ""

OpenServiceMesh:
  ignoreNamespaces: "kube-system azure-arc arc-osm-system"
  testedDistros: "aks gke eks openshift rancher_rke"

osm:
  osm:
    enableDebugServer: false
    enablePermissiveTrafficPolicy: true
    image:
      registry: mcr.microsoft.com/oss/openservicemesh
      tag: v1.1.1
    enforceSingleMesh: true
    enableReconciler: true
    deployPrometheus: false
    deployJaeger: false
    webhookConfigNamePrefix: arc-osm-webhook
    sidecarImage: mcr.microsoft.com/oss/envoyproxy/envoy:v1.19.3
    osmController:
      podLabels: {
        app.kubernetes.io/component: osm-controller
      }
    injector:
      podLabels: {
        app.kubernetes.io/component: osm-controller
      }
    prometheus:
      image: mcr.microsoft.com/oss/prometheus/prometheus:v2.34.0
    curlImage: mcr.microsoft.com/oss/tutum/curl
    tracing:
      image: mcr.microsoft.com/oss/jaegertracing/all-in-one
    grafana:
      image: mcr.microsoft.com/oss/grafana/grafana:v8.2.2
      rendererImage: mcr.microsoft.com/oss/grafana/grafana-image-renderer:v3.2.1
  contour:
    contour:
      registry: mcr.microsoft.com
      repository: oss/contour/contour
    envoy:
      registry: mcr.microsoft.com
      repository: oss/envoyproxy/envoy

alpine:
  image:
    name: "mcr.microsoft.com/azure-policy/alpine"
    tag: "prod_20200505.1"
