name: Go
on: 
  push:
    branches:
      -main
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
    end-to-end:
      name: End to end test
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - name: Setup Go 1.15
          uses: actions/setup-go@v1
          with:
            go-version: 1.15
          id: go