name: Release Helm Chart
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@a83e2c28c4d5d4eb23b272be8167de475153d109 # v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
