name: PR Gate
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
jobs:

  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Bootstrap e2e
      run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
          make e2e-bootstrap

    - name: Install helm chart for e2e
      run: |
          make e2e-helm-deploy
          
    - name: Run e2e
      run: |
        make test-e2e

    - name: Cleanup e2e
      run: |
        make e2e-cleanup
